project_id = "kxohdhxhnsdntxfwmxir"

[functions.stripe-webhook]
verify_jwt = false

[functions.get-my-orders]
verify_jwt = false

[functions.get-order-by-session]
verify_jwt = false

[functions.create-billing-portal]
verify_jwt = false

[functions.validate-exotic-code]
verify_jwt = false

[functions.check-vital-access]
verify_jwt = false

[functions.start-vital-trial]
verify_jwt = false
